FROM node:16-alpine
WORKDIR /app
RUN chown -R node:node .
USER node
COPY --chown=node:node package.json ./
RUN npm i --production
COPY --chown=node:node dist ./dist
EXPOSE 3000
CMD ["node", "dist/main"]